services:

  app:
    build:
      context: .

    ports:
      - "8000:8000"

    command: bash -c "python main.py"

    depends_on:
      - redis

  redis:
     image: redis:7.0-alpine
     container_name: parser_redis
     ports:
       - "6379:6379"
     command: redis-server --appendonly yes
     volumes:
       - redis_data:/data

  celery_worker:
    build:
      context: .
    command: bash -c "celery -A celery_worker:celery_app worker --loglevel=INFO"

    depends_on:
      - redis

volumes:
  redis_data: {}